### ISSUE TITLE
Changes to handle 2.16.0 Session Changes / API

### ISSUE THREAD

**Issue by banagale** [marcsello/pyopenvidu#14]
Curious if you have eyes on the 2.16.0 update. I have been working on other parts of my app,  but am planning to start testing the update against my implementation of pyopenvidu soon.

Not sure if / how much breaking changes there might be. But there are at least a few new things like token invalidation that probably can get added.

**Comment by marcsello** [comment]
Hey! Yes, I do planning updating this package to support the latest features, I'm just kind of short on free time currently. ^^"

**Comment by banagale** [comment]
Okay, I may be able to get a PR in--I just wanted to make sure you didn't have much work done on it yet.

**Comment by marcsello** [comment]
The latest release implements support for OpenVidu server 2.16.0. It should be available in a few minutes when the CI job is done.

**Comment by banagale** [comment]
Thanks! I had to take a break from OV work to focus on another project but plan to come back to it in the new year. Will give feedback then!
