### ISSUE TITLE
get_sessions() method is referenced in examples but it is a property now

### ISSUE THREAD

**Issue by banagale** [marcsello/pyopenvidu#9]
As of [this commit](https://github.com/marcsello/pyopenvidu/commit/6fab17af7722a63c089681281b4ee785e1947571), openvidu.get_sessions() is now just sessions.

This should be reflected in the example docs.

Will submit PR.

**Comment by marcsello** [comment]
Hey!

Thank you for fixing this. It seems like it slipped between the cracks when I've changed the method to property.

**Comment by banagale** [comment]
@marcsello You're welcome. I added [a question](https://github.com/marcsello/pyopenvidu/issues/11) based on my parsing of your library so far and understanding of OpenVidu. It may be better targeted at the main repo / maintainers, if you want me to redirect it there, just let me know.
